/**
* This file was automatically generated by @oraichain/ts-codegen@0.35.8.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @oraichain/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import {Uint128, Coin} from "./types";
import {InstantiateMsg, ExecuteMsg, Metadata, DenomUnit, QueryMsg, SudoMsg, BlacklisteesResponse, StatusInfo, BlacklisterAllowancesResponse, AllowanceResponse, AllowancesResponse, AllowanceInfo, DenomResponse, FreezerAllowancesResponse, StatusResponse, IsFrozenResponse, OwnerResponse, WhitelisteesResponse, WhitelisterAllowancesResponse} from "./CwTokenfactoryIssuer.types";
export interface CwTokenfactoryIssuerReadOnlyInterface {
  contractAddress: string;
  isFrozen: () => Promise<IsFrozenResponse>;
  denom: () => Promise<DenomResponse>;
  owner: () => Promise<OwnerResponse>;
  burnAllowance: ({
    address
  }: {
    address: string;
  }) => Promise<AllowanceResponse>;
  burnAllowances: ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }) => Promise<AllowancesResponse>;
  mintAllowance: ({
    address
  }: {
    address: string;
  }) => Promise<AllowanceResponse>;
  mintAllowances: ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }) => Promise<AllowancesResponse>;
  isBlacklisted: ({
    address
  }: {
    address: string;
  }) => Promise<StatusResponse>;
  blacklistees: ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }) => Promise<BlacklisteesResponse>;
  isBlacklister: ({
    address
  }: {
    address: string;
  }) => Promise<StatusResponse>;
  blacklisterAllowances: ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }) => Promise<BlacklisterAllowancesResponse>;
  isWhitelisted: ({
    address
  }: {
    address: string;
  }) => Promise<StatusResponse>;
  whitelistees: ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }) => Promise<WhitelisteesResponse>;
  isWhitelister: ({
    address
  }: {
    address: string;
  }) => Promise<StatusResponse>;
  whitelisterAllowances: ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }) => Promise<WhitelisterAllowancesResponse>;
  isFreezer: ({
    address
  }: {
    address: string;
  }) => Promise<StatusResponse>;
  freezerAllowances: ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }) => Promise<FreezerAllowancesResponse>;
}
export class CwTokenfactoryIssuerQueryClient implements CwTokenfactoryIssuerReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.isFrozen = this.isFrozen.bind(this);
    this.denom = this.denom.bind(this);
    this.owner = this.owner.bind(this);
    this.burnAllowance = this.burnAllowance.bind(this);
    this.burnAllowances = this.burnAllowances.bind(this);
    this.mintAllowance = this.mintAllowance.bind(this);
    this.mintAllowances = this.mintAllowances.bind(this);
    this.isBlacklisted = this.isBlacklisted.bind(this);
    this.blacklistees = this.blacklistees.bind(this);
    this.isBlacklister = this.isBlacklister.bind(this);
    this.blacklisterAllowances = this.blacklisterAllowances.bind(this);
    this.isWhitelisted = this.isWhitelisted.bind(this);
    this.whitelistees = this.whitelistees.bind(this);
    this.isWhitelister = this.isWhitelister.bind(this);
    this.whitelisterAllowances = this.whitelisterAllowances.bind(this);
    this.isFreezer = this.isFreezer.bind(this);
    this.freezerAllowances = this.freezerAllowances.bind(this);
  }

  isFrozen = async (): Promise<IsFrozenResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      is_frozen: {}
    });
  };
  denom = async (): Promise<DenomResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      denom: {}
    });
  };
  owner = async (): Promise<OwnerResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      owner: {}
    });
  };
  burnAllowance = async ({
    address
  }: {
    address: string;
  }): Promise<AllowanceResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      burn_allowance: {
        address
      }
    });
  };
  burnAllowances = async ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }): Promise<AllowancesResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      burn_allowances: {
        limit,
        start_after: startAfter
      }
    });
  };
  mintAllowance = async ({
    address
  }: {
    address: string;
  }): Promise<AllowanceResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      mint_allowance: {
        address
      }
    });
  };
  mintAllowances = async ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }): Promise<AllowancesResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      mint_allowances: {
        limit,
        start_after: startAfter
      }
    });
  };
  isBlacklisted = async ({
    address
  }: {
    address: string;
  }): Promise<StatusResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      is_blacklisted: {
        address
      }
    });
  };
  blacklistees = async ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }): Promise<BlacklisteesResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      blacklistees: {
        limit,
        start_after: startAfter
      }
    });
  };
  isBlacklister = async ({
    address
  }: {
    address: string;
  }): Promise<StatusResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      is_blacklister: {
        address
      }
    });
  };
  blacklisterAllowances = async ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }): Promise<BlacklisterAllowancesResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      blacklister_allowances: {
        limit,
        start_after: startAfter
      }
    });
  };
  isWhitelisted = async ({
    address
  }: {
    address: string;
  }): Promise<StatusResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      is_whitelisted: {
        address
      }
    });
  };
  whitelistees = async ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }): Promise<WhitelisteesResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      whitelistees: {
        limit,
        start_after: startAfter
      }
    });
  };
  isWhitelister = async ({
    address
  }: {
    address: string;
  }): Promise<StatusResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      is_whitelister: {
        address
      }
    });
  };
  whitelisterAllowances = async ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }): Promise<WhitelisterAllowancesResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      whitelister_allowances: {
        limit,
        start_after: startAfter
      }
    });
  };
  isFreezer = async ({
    address
  }: {
    address: string;
  }): Promise<StatusResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      is_freezer: {
        address
      }
    });
  };
  freezerAllowances = async ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }): Promise<FreezerAllowancesResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      freezer_allowances: {
        limit,
        start_after: startAfter
      }
    });
  };
}
export interface CwTokenfactoryIssuerInterface extends CwTokenfactoryIssuerReadOnlyInterface {
  contractAddress: string;
  sender: string;
  changeTokenFactoryAdmin: ({
    newAdmin
  }: {
    newAdmin: string;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  changeContractOwner: ({
    newOwner
  }: {
    newOwner: string;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  setDenomMetadata: ({
    metadata
  }: {
    metadata: Metadata;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  setMinterAllowance: ({
    address,
    allowance
  }: {
    address: string;
    allowance: Uint128;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  setBurnerAllowance: ({
    address,
    allowance
  }: {
    address: string;
    allowance: Uint128;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  setBlacklister: ({
    address,
    status
  }: {
    address: string;
    status: boolean;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  setWhitelister: ({
    address,
    status
  }: {
    address: string;
    status: boolean;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  setBeforeSendHook: (_fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  setFreezer: ({
    address,
    status
  }: {
    address: string;
    status: boolean;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  mint: ({
    amount,
    toAddress
  }: {
    amount: Uint128;
    toAddress: string;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  burn: ({
    amount,
    fromAddress
  }: {
    amount: Uint128;
    fromAddress: string;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  blacklist: ({
    address,
    status
  }: {
    address: string;
    status: boolean;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  whitelist: ({
    address,
    status
  }: {
    address: string;
    status: boolean;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  freeze: ({
    status
  }: {
    status: boolean;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  forceTransfer: ({
    amount,
    fromAddress,
    toAddress
  }: {
    amount: Uint128;
    fromAddress: string;
    toAddress: string;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class CwTokenfactoryIssuerClient extends CwTokenfactoryIssuerQueryClient implements CwTokenfactoryIssuerInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.changeTokenFactoryAdmin = this.changeTokenFactoryAdmin.bind(this);
    this.changeContractOwner = this.changeContractOwner.bind(this);
    this.setDenomMetadata = this.setDenomMetadata.bind(this);
    this.setMinterAllowance = this.setMinterAllowance.bind(this);
    this.setBurnerAllowance = this.setBurnerAllowance.bind(this);
    this.setBlacklister = this.setBlacklister.bind(this);
    this.setWhitelister = this.setWhitelister.bind(this);
    this.setBeforeSendHook = this.setBeforeSendHook.bind(this);
    this.setFreezer = this.setFreezer.bind(this);
    this.mint = this.mint.bind(this);
    this.burn = this.burn.bind(this);
    this.blacklist = this.blacklist.bind(this);
    this.whitelist = this.whitelist.bind(this);
    this.freeze = this.freeze.bind(this);
    this.forceTransfer = this.forceTransfer.bind(this);
  }

  changeTokenFactoryAdmin = async ({
    newAdmin
  }: {
    newAdmin: string;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      change_token_factory_admin: {
        new_admin: newAdmin
      }
    }, _fee, _memo, _funds);
  };
  changeContractOwner = async ({
    newOwner
  }: {
    newOwner: string;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      change_contract_owner: {
        new_owner: newOwner
      }
    }, _fee, _memo, _funds);
  };
  setDenomMetadata = async ({
    metadata
  }: {
    metadata: Metadata;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_denom_metadata: {
        metadata
      }
    }, _fee, _memo, _funds);
  };
  setMinterAllowance = async ({
    address,
    allowance
  }: {
    address: string;
    allowance: Uint128;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_minter_allowance: {
        address,
        allowance
      }
    }, _fee, _memo, _funds);
  };
  setBurnerAllowance = async ({
    address,
    allowance
  }: {
    address: string;
    allowance: Uint128;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_burner_allowance: {
        address,
        allowance
      }
    }, _fee, _memo, _funds);
  };
  setBlacklister = async ({
    address,
    status
  }: {
    address: string;
    status: boolean;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_blacklister: {
        address,
        status
      }
    }, _fee, _memo, _funds);
  };
  setWhitelister = async ({
    address,
    status
  }: {
    address: string;
    status: boolean;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_whitelister: {
        address,
        status
      }
    }, _fee, _memo, _funds);
  };
  setBeforeSendHook = async (_fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_before_send_hook: {}
    }, _fee, _memo, _funds);
  };
  setFreezer = async ({
    address,
    status
  }: {
    address: string;
    status: boolean;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_freezer: {
        address,
        status
      }
    }, _fee, _memo, _funds);
  };
  mint = async ({
    amount,
    toAddress
  }: {
    amount: Uint128;
    toAddress: string;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      mint: {
        amount,
        to_address: toAddress
      }
    }, _fee, _memo, _funds);
  };
  burn = async ({
    amount,
    fromAddress
  }: {
    amount: Uint128;
    fromAddress: string;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      burn: {
        amount,
        from_address: fromAddress
      }
    }, _fee, _memo, _funds);
  };
  blacklist = async ({
    address,
    status
  }: {
    address: string;
    status: boolean;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      blacklist: {
        address,
        status
      }
    }, _fee, _memo, _funds);
  };
  whitelist = async ({
    address,
    status
  }: {
    address: string;
    status: boolean;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      whitelist: {
        address,
        status
      }
    }, _fee, _memo, _funds);
  };
  freeze = async ({
    status
  }: {
    status: boolean;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      freeze: {
        status
      }
    }, _fee, _memo, _funds);
  };
  forceTransfer = async ({
    amount,
    fromAddress,
    toAddress
  }: {
    amount: Uint128;
    fromAddress: string;
    toAddress: string;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      force_transfer: {
        amount,
        from_address: fromAddress,
        to_address: toAddress
      }
    }, _fee, _memo, _funds);
  };
}